feat: replace video components wip
voorhoede/voorhoede-website pull request #711
Opened 2023-06-30 13:40 UTC by Arash217

## What changes were made

## How to test or check results

## Checks
- [ ] All content model changes are done through [scripted migrations](../readme.md#scripted-migrations)
- [ ] Appointed PR reviewers

2023-07-07 12:30 UTC, Siilwyn requested changes
Nice improvement overall! Left some small remarks

2023-07-07 12:30 UTC, Siilwyn commented on src/components/responsive-video/responsive-video.vue
> +  margin-top: 0.5rem;
Let's use a spacing variable for this.

2023-07-07 12:30 UTC, Siilwyn commented on src/components/responsive-video/responsive-video.vue
> +  transform: translate(-50%, -50%);
Is there a way to simplify the centering by using flexbox?

2023-07-07 13:48 UTC, Siilwyn approved these changes

2023-07-13 12:05 UTC, Frankwarnaar commented
Are we waiting for anything to merge this? @Arash217 @Siilwyn

2023-09-08 12:16 UTC, merged