feat/improve-blog-post-headings
voorhoede/voorhoede-website pull request #804
Opened 2024-06-10 14:23 UTC by WesselSmit

## What changes were made

The blog posts had a heading mapping that caused some issues. Each blog posts exists of multiple text-record blocks which include a explicit title field and a rich-text field (which can also include all heading levels). The explicit titles were being mapped to always be shown as a level smaller, but this sometimes caused the explicit title to be the exact same size visually as the next heading in the rich text.
E.g if the explicit title is level 2, but due to the mapping, is being rendered as a h3, and if the rich text starts with a heading that is also level 3 --> then both these headings would have the same size and look visually identical, even though one of the headings is a h2 and the other is a h3 (this scenario is shown in the screenshot below).

![Screenshot 2024-06-10 at 16 19 34](https://github.com/voorhoede/voorhoede-website/assets/45405413/d8efc1ad-a98c-4019-b368-5d260b72e294)

To prevent this, me and Vera came up with the idea to adjust the blog post heading font-sizes to be unique -- this means they do not match the .h1-.h6 classes that we have specified in the typography.css file and thus never clash with the rich-text headings. But this does mean that we make an exception for the heading sizes in the blog posts. 

## How to test or check results

- check the blog posts

## Checks
- [x] All content model changes are done through [scripted migrations](../readme.md#scripted-migrations)
- [x] Appointed PR reviewers

2024-06-11 08:59 UTC, decrek requested changes

2024-06-11 08:59 UTC, decrek commented on src/pages/[language]/blog/[slug]/index.vue
> +  .page-blog-post-list__title--h2 {
we have these styles already defined in typography, why are we doing typography styling again?

2024-06-11 08:59 UTC, decrek commented on src/pages/[language]/blog/[slug]/index.vue
> +              ${headingLevelClassMap[item.headingLevel || defaultHeadingLevel]}
It feels like this is set up too complicated and now we are complicating it more

2024-06-11 09:34 UTC, WesselSmit commented
> Would this work? Render all section titles as h2's and all other headings as h3's, removing the heading level CMS option and all of the heading mapping logic. The result will be semantic HTML, i.e. not skipping heading levels, and visually distinguishable headings.

@decrek I think this would work, but maybe the rich-text headings should be h3-h6 instead of always being a h3?

@Siilwyn do you have any thoughts on this?

2024-06-11 12:47 UTC, Siilwyn commented
@WesselSmit not sure I fully understand the issue and context but Declan's suggestion does sound like a good solution as it reduces complexity. Keeping the option for two 'levels' of headings within a post is reasonable, I mainly wonder if it's used at the moment though. If not, we could keep it simple.

I still dream of changing the blog posts to markdown but not relevant for now. :thought_balloon:

2024-06-14 13:21 UTC, WesselSmit commented
@decrek @Siilwyn closing this PR in favor of the new implementation as seen in https://github.com/voorhoede/voorhoede-website/pull/806

2024-06-14 13:21 UTC, closed without merging